name: Build & push image for main

on:
  push:
    branches: ['main']

permissions:
  id-token: write
  contents: read

jobs:
  build-and-push-image:
    name: Build and push Docker image
    uses: larsselbekk/github-actions/.github/workflows/build-and-push-image.yml@main
